config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]
  get 'welcome/index'
  get 'about', to: "welcome#about"
  get 'welcome/contact'
  resources :advertisements
  resources :topics do
  	resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
      resources :comments, only: [:create, :destroy]
      resources :summaries, except: [:index]
      resources :favorites, only: [:create, :destroy]

      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  root to: 'welcome#index'
end

app/models/summary.rb
class Summary < ActiveRecord::Base
  belongs_to :post
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  def show
  	@post = Post.find(params[:post_id])
  	@summary = Summary.find(params[:id])
  	authorize @summary
  end

  def new
  	@topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:post_id])
  	@summary = Summary.new
  	authorize @summary
  end

  def edit
  	@post = Post.find(params[:post_id])
  	@summary = Summary.find(params[:id])
  	@topic = Topic.find(params[:topic_id])
  	authorize @summary
  end

  def create
  	@summary = Summary.new(params.require(:summary).permit(:body))
  	@topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:post_id])
  	@summary.post = @post
  	authorize @summary
  	if @summary.save
  		flash[:notice] = "Summary was saved"
  		redirect_to [@topic, @post, @summary]
  	else
  		flash[:error] = "Summary was not saved. Please try again"
  		render :new
  	end
  end

  def update
  	@summary = Summary.find(params[:id])
  	@topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:post_id])
  	@summary.post = @post
  	authorize @summary
  	if @summary.update_attributes(params.require(:summary).permit(:body))
  		flash[:notice] = "Summary was updated"
  		redirect_to [@topic, @post, @summary]
  	else
  		flash[:error] = "Summary was not updated. Please try again"
  		render :new
  	end
  end
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/summaries/edit.html.erb
<h1><%= @post.title %></h1>


<div class="row">
	<%= form_for [@topic, @post, @summary] do |f| %>
		<div class="form-group">
			<%= f.label :summary %>
			<%= f.text_area :body %>
		</div>
		<%= f.submit "Save" %>
	<% end %>
</div>

app/views/summaries/new.html.erb
<h1><%= @post.title %></h1>

<div class="row">
	<%= form_for [@topic, @post, @summary] do |f| %>
		<div class="form-group">
			<%= f.label :summary %>
			<%= f.text_area :body %>
		</div>
		<%= f.submit "Save" %>
	<% end %>
</div>

app/views/summaries/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to "Edit", edit_topic_post_summary_path %>

<p><%= @summary.body %></p>